import { makeAutoObservable, observable } from 'mobx';

class AudioStore {
    volume = 30
    currentSongIndex = 0;
    position = 0;
    newPos = -1
    play = false;
    category = 'Main'
    songs = [
        "https://knut.wtf/music/Main/Candy Shop - 50 Cent.mp3",
        "https://knut.wtf/music/Main/American Boy (feat. Kanye West) - Estelle.mp3",
        "https://knut.wtf/music/Main/A Thousand Miles - Vanessa Carlton.mp3",
        "https://knut.wtf/music/Main/Ab in Den Süden - Buddy.mp3",
        "https://knut.wtf/music/Main/All The Things She Said - t.A.T.u..mp3",
        "https://knut.wtf/music/Main/Around the World (La La La La La) - Radio Version - A Touch Of Class.mp3",
        "https://knut.wtf/music/Main/Be My Lover - La Bouche.mp3",
        "https://knut.wtf/music/Main/Beautiful - Snoop Dogg.mp3",
        "https://knut.wtf/music/Main/Because I Got High - Afroman.mp3",
        "https://knut.wtf/music/Main/Blue (Da Ba Dee) - Gabry Ponte Ice Pop Radio - Eiffel 65.mp3",
        "https://knut.wtf/music/Main/Butterfly - Crazy Town.mp3",
        "https://knut.wtf/music/Main/Cry Me a River - Justin Timberlake.mp3",
        "https://knut.wtf/music/Main/Crying at the Discoteque - Radio Edit - Alcazar.mp3",
        "https://knut.wtf/music/Main/Don't Stop The Music - Rihanna.mp3",
        "https://knut.wtf/music/Main/Everytime We Touch - Radio Edit - Cascada.mp3",
        "https://knut.wtf/music/Main/Hamma! - Single Edit - Culcha Candela.mp3",
        "https://knut.wtf/music/Main/Hips Don't Lie (feat. Wyclef Jean) - Shakira.mp3",
        "https://knut.wtf/music/Main/I'll Be Missing You (feat. Faith Evans, 112) - Diddy.mp3",
        "https://knut.wtf/music/Main/In Da Club - 50 Cent.mp3",
        "https://knut.wtf/music/Main/Lonely - Akon.mp3",
        "https://knut.wtf/music/Main/Low (feat. T-Pain) - Flo Rida.mp3",
        "https://knut.wtf/music/Main/Milkshake - Kelis.mp3",
        "https://knut.wtf/music/Main/Ms. Jackson - Outkast.mp3",
        "https://knut.wtf/music/Main/Numb - Linkin Park.mp3",
        "https://knut.wtf/music/Main/One More Time - Daft Punk.mp3",
        "https://knut.wtf/music/Main/Oops!...I Did It Again - Britney Spears.mp3",
        "https://knut.wtf/music/Main/Promiscuous - Nelly Furtado.mp3",
        "https://knut.wtf/music/Main/Relax, Take It Easy - MIKA.mp3",
        "https://knut.wtf/music/Main/savernames.js",
        "https://knut.wtf/music/Main/SexyBack (feat. Timbaland) - Justin Timberlake.mp3",
        "https://knut.wtf/music/Main/SOS - Radio Edit - Rihanna.mp3",
        "https://knut.wtf/music/Main/Stronger - Kanye West.mp3",
        "https://knut.wtf/music/Main/Summer Jam - Radio Edit - The Underdog Project.mp3",
        "https://knut.wtf/music/Main/Toxic - Britney Spears.mp3",
        "https://knut.wtf/music/Main/Waka Waka (This Time for Africa) (feat. Freshlyground) - Shakira.mp3",
        "https://knut.wtf/music/Main/When Love Takes Over (feat. Kelly Rowland) - David Guetta.mp3",
        "https://knut.wtf/music/Main/Without Me - Eminem.mp3"
    ].sort(() => Math.random() - 0.5)
    constructor() {
        makeAutoObservable(this);
    }

    setVolume(vol) {
        if (vol <= 100) {
            if (vol >= 0) {
                this.volume = vol
            } else {
                this.volume = 0
            }
        } else {
            this.volume = 100
        }
    }
    setPosition(pos) {
        if (pos <= 100) {
            if (pos >= 0) {
                this.position = pos
            } else {
                this.position = 0
            }
        } else {
            this.position = 100
        }
    }

    nextSong() {
        if (this.currentSongIndex + 1 < this.songs.length) {
            this.currentSongIndex = this.currentSongIndex + 1
        } else {
            this.currentSongIndex = 0
        }
        this.newPos = 0 + Math.random() / 10
    }
    prevSong() {
        if (this.currentSongIndex - 1 > 0) {
            this.currentSongIndex = this.currentSongIndex - 1
        } else {
            this.currentSongIndex = this.songs.length - 1
        }
        this.newPos = 0 + Math.random() / 10

    }

    changeCategory(cat) {
        console.log('change');
        console.log(cat);

        if (cat === 'Main') {
            this.songs = [
                "https://knut.wtf/music/Main/Candy Shop - 50 Cent.mp3",
                "https://knut.wtf/music/Main/American Boy (feat. Kanye West) - Estelle.mp3",
                "https://knut.wtf/music/Main/A Thousand Miles - Vanessa Carlton.mp3",
                "https://knut.wtf/music/Main/Ab in Den Süden - Buddy.mp3",
                "https://knut.wtf/music/Main/All The Things She Said - t.A.T.u..mp3",
                "https://knut.wtf/music/Main/Around the World (La La La La La) - Radio Version - A Touch Of Class.mp3",
                "https://knut.wtf/music/Main/Be My Lover - La Bouche.mp3",
                "https://knut.wtf/music/Main/Beautiful - Snoop Dogg.mp3",
                "https://knut.wtf/music/Main/Because I Got High - Afroman.mp3",
                "https://knut.wtf/music/Main/Blue (Da Ba Dee) - Gabry Ponte Ice Pop Radio - Eiffel 65.mp3",
                "https://knut.wtf/music/Main/Butterfly - Crazy Town.mp3",
                "https://knut.wtf/music/Main/Cry Me a River - Justin Timberlake.mp3",
                "https://knut.wtf/music/Main/Crying at the Discoteque - Radio Edit - Alcazar.mp3",
                "https://knut.wtf/music/Main/Don't Stop The Music - Rihanna.mp3",
                "https://knut.wtf/music/Main/Everytime We Touch - Radio Edit - Cascada.mp3",
                "https://knut.wtf/music/Main/Hamma! - Single Edit - Culcha Candela.mp3",
                "https://knut.wtf/music/Main/Hips Don't Lie (feat. Wyclef Jean) - Shakira.mp3",
                "https://knut.wtf/music/Main/I'll Be Missing You (feat. Faith Evans, 112) - Diddy.mp3",
                "https://knut.wtf/music/Main/In Da Club - 50 Cent.mp3",
                "https://knut.wtf/music/Main/Lonely - Akon.mp3",
                "https://knut.wtf/music/Main/Low (feat. T-Pain) - Flo Rida.mp3",
                "https://knut.wtf/music/Main/Milkshake - Kelis.mp3",
                "https://knut.wtf/music/Main/Ms. Jackson - Outkast.mp3",
                "https://knut.wtf/music/Main/Numb - Linkin Park.mp3",
                "https://knut.wtf/music/Main/One More Time - Daft Punk.mp3",
                "https://knut.wtf/music/Main/Oops!...I Did It Again - Britney Spears.mp3",
                "https://knut.wtf/music/Main/Promiscuous - Nelly Furtado.mp3",
                "https://knut.wtf/music/Main/Relax, Take It Easy - MIKA.mp3",
                "https://knut.wtf/music/Main/savernames.js",
                "https://knut.wtf/music/Main/SexyBack (feat. Timbaland) - Justin Timberlake.mp3",
                "https://knut.wtf/music/Main/SOS - Radio Edit - Rihanna.mp3",
                "https://knut.wtf/music/Main/Stronger - Kanye West.mp3",
                "https://knut.wtf/music/Main/Summer Jam - Radio Edit - The Underdog Project.mp3",
                "https://knut.wtf/music/Main/Toxic - Britney Spears.mp3",
                "https://knut.wtf/music/Main/Waka Waka (This Time for Africa) (feat. Freshlyground) - Shakira.mp3",
                "https://knut.wtf/music/Main/When Love Takes Over (feat. Kelly Rowland) - David Guetta.mp3",
                "https://knut.wtf/music/Main/Without Me - Eminem.mp3"
            ].sort(() => Math.random() - 0.5)
        }
        if (cat === 'ChillMorning') {
            this.songs = ["https://knut.wtf/music/ChillMorning/A Bar Song (Tipsy).mp3",
                "https://knut.wtf/music/ChillMorning/APT..mp3",
                "https://knut.wtf/music/ChillMorning/Austin (Boots Stop Workin').mp3",
                "https://knut.wtf/music/ChillMorning/Autumn Remains.mp3",
                "https://knut.wtf/music/ChillMorning/Be Easy - Nikko Mad Mix.mp3",
                "https://knut.wtf/music/ChillMorning/Beautiful Things.mp3",
                "https://knut.wtf/music/ChillMorning/BIRDS OF A FEATHER.mp3",
                "https://knut.wtf/music/ChillMorning/Black Friday (pretty like the sun).mp3",
                "https://knut.wtf/music/ChillMorning/Chemicals.mp3",
                "https://knut.wtf/music/ChillMorning/circles.mp3",
                "https://knut.wtf/music/ChillMorning/Clocks - Sign of the Times Remix.mp3",
                "https://knut.wtf/music/ChillMorning/Clocks.mp3",
                "https://knut.wtf/music/ChillMorning/Colourblind.mp3",
                "https://knut.wtf/music/ChillMorning/CONTIGO (with Tiësto).mp3",
                "https://knut.wtf/music/ChillMorning/Creepin' (with The Weeknd & 21 Savage).mp3",
                "https://knut.wtf/music/ChillMorning/Dance The Night - From Barbie The Album.mp3",
                "https://knut.wtf/music/ChillMorning/Die With A Smile.mp3",
                "https://knut.wtf/music/ChillMorning/Don't Mind.mp3",
                "https://knut.wtf/music/ChillMorning/Dream.mp3",
                "https://knut.wtf/music/ChillMorning/drown.mp3",
                "https://knut.wtf/music/ChillMorning/Espresso.mp3",
                "https://knut.wtf/music/ChillMorning/Eyes Closed.mp3",
                "https://knut.wtf/music/ChillMorning/Fast Car.mp3",
                "https://knut.wtf/music/ChillMorning/feelslikeimfallinginlove.mp3",
                "https://knut.wtf/music/ChillMorning/Flowers.mp3",
                "https://knut.wtf/music/ChillMorning/For Life (feat. Nile Rodgers).mp3",
                "https://knut.wtf/music/ChillMorning/For My Hand (feat. Ed Sheeran).mp3",
                "https://knut.wtf/music/ChillMorning/Forever (feat. Malou & Yuna).mp3",
                "https://knut.wtf/music/ChillMorning/greedy.mp3",
                "https://knut.wtf/music/ChillMorning/Hold On Me.mp3",
                "https://knut.wtf/music/ChillMorning/Houdini.mp3",
                "https://knut.wtf/music/ChillMorning/I Don't Wanna Wait.mp3",
                "https://knut.wtf/music/ChillMorning/I Had Some Help (Feat. Morgan Wallen).mp3",
                "https://knut.wtf/music/ChillMorning/i like the way you kiss me.mp3",
                "https://knut.wtf/music/ChillMorning/I'm Good (Blue).mp3",
                "https://knut.wtf/music/ChillMorning/It's Not Right But It's Okay.mp3",
                "https://knut.wtf/music/ChillMorning/Journey.mp3",
                "https://knut.wtf/music/ChillMorning/June.mp3",
                "https://knut.wtf/music/ChillMorning/Kill Bill.mp3",
                "https://knut.wtf/music/ChillMorning/LET GO.mp3",
                "https://knut.wtf/music/ChillMorning/Let Her Go - Lost Coconut Remix.mp3",
                "https://knut.wtf/music/ChillMorning/Life.mp3",
                "https://knut.wtf/music/ChillMorning/Lift Me Up.mp3",
                "https://knut.wtf/music/ChillMorning/Long Island.mp3",
                "https://knut.wtf/music/ChillMorning/Lose Control.mp3",
                "https://knut.wtf/music/ChillMorning/Louder.mp3",
                "https://knut.wtf/music/ChillMorning/Love Is The Only Thing.mp3",
                "https://knut.wtf/music/ChillMorning/Lovers In A Past Life (with Rag'n'Bone Man).mp3",
                "https://knut.wtf/music/ChillMorning/Lovin On Me.mp3",
                "https://knut.wtf/music/ChillMorning/Midnight.mp3",
                "https://knut.wtf/music/ChillMorning/Move.mp3",
                "https://knut.wtf/music/ChillMorning/My Love Mine All Mine.mp3",
                "https://knut.wtf/music/ChillMorning/Mystery.mp3",
                "https://knut.wtf/music/ChillMorning/Need 2.mp3",
                "https://knut.wtf/music/ChillMorning/Never Going Home Tonight (feat. Madison Love).mp3",
                "https://knut.wtf/music/ChillMorning/Never Gonna Not Dance Again.mp3",
                "https://knut.wtf/music/ChillMorning/Nevermind.mp3",
                "https://knut.wtf/music/ChillMorning/Nowhere To Go.mp3",
                "https://knut.wtf/music/ChillMorning/Oh My Love.mp3",
                "https://knut.wtf/music/ChillMorning/One More Time.mp3",
                "https://knut.wtf/music/ChillMorning/Paint The Town Red.mp3",
                "https://knut.wtf/music/ChillMorning/Paradise.mp3",
                "https://knut.wtf/music/ChillMorning/Porque Te Vas.mp3",
                "https://knut.wtf/music/ChillMorning/RUNAWAY.mp3",
                "https://knut.wtf/music/ChillMorning/Sad Love (feat. JAIKO).mp3",
                "https://knut.wtf/music/ChillMorning/Say Say Say - Lost Coconut Remix.mp3",
                "https://knut.wtf/music/ChillMorning/Shakira_ Bzrp Music Sessions, Vol. 53.mp3",
                "https://knut.wtf/music/ChillMorning/Smile (feat. Carolina Liar).mp3",
                "https://knut.wtf/music/ChillMorning/Something Just Like This.mp3",
                "https://knut.wtf/music/ChillMorning/Speed of Sound - Ronan Remix.mp3",
                "https://knut.wtf/music/ChillMorning/Sprinter.mp3",
                "https://knut.wtf/music/ChillMorning/Stargazing.mp3",
                "https://knut.wtf/music/ChillMorning/Strangers.mp3",
                "https://knut.wtf/music/ChillMorning/Stumblin' In.mp3",
                "https://knut.wtf/music/ChillMorning/Sweater Weather.mp3",
                "https://knut.wtf/music/ChillMorning/Talk About Us.mp3",
                "https://knut.wtf/music/ChillMorning/TEXAS HOLD 'EM.mp3",
                "https://knut.wtf/music/ChillMorning/The Feeling.mp3",
                "https://knut.wtf/music/ChillMorning/The Hard Way.mp3",
                "https://knut.wtf/music/ChillMorning/The Joker And The Queen (feat. Taylor Swift).mp3",
                "https://knut.wtf/music/ChillMorning/The Sound of Silence - CYRIL Remix.mp3",
                "https://knut.wtf/music/ChillMorning/This Is The Night - Radio Edit.mp3",
                "https://knut.wtf/music/ChillMorning/THOUSAND MILES.mp3",
                "https://knut.wtf/music/ChillMorning/Too Sweet.mp3",
                "https://knut.wtf/music/ChillMorning/Training Season.mp3",
                "https://knut.wtf/music/ChillMorning/vampire.mp3",
                "https://knut.wtf/music/ChillMorning/Viva La Vida.mp3",
                "https://knut.wtf/music/ChillMorning/Wait - Kygo Remix (2024 Edit).mp3",
                "https://knut.wtf/music/ChillMorning/Waste (feat. Veronica Bravo).mp3",
                "https://knut.wtf/music/ChillMorning/Water.mp3",
                "https://knut.wtf/music/ChillMorning/we can't be friends (wait for your love).mp3",
                "https://knut.wtf/music/ChillMorning/What Was I Made For_ [From The Motion Picture _Barbie_].mp3",
                "https://knut.wtf/music/ChillMorning/What Would You Do.mp3",
                "https://knut.wtf/music/ChillMorning/Whatever.mp3",
                "https://knut.wtf/music/ChillMorning/Wonderful Life.mp3",
                "https://knut.wtf/music/ChillMorning/yes, and_.mp3",
                "https://knut.wtf/music/ChillMorning/Your Heart.mp3"].sort(() => Math.random() - 0.5)
        }
        if (cat === 'Driving') {
            this.songs = ["https://knut.wtf/music/Driving/2BIPOLAR.mp3",
                "https://knut.wtf/music/Driving/50k.mp3",
                "https://knut.wtf/music/Driving/9mm.mp3",
                "https://knut.wtf/music/Driving/Alors on danse.mp3",
                "https://knut.wtf/music/Driving/Another Story.mp3",
                "https://knut.wtf/music/Driving/AVANGARD.mp3",
                "https://knut.wtf/music/Driving/Babel - Slowed.mp3",
                "https://knut.wtf/music/Driving/BAIXO.mp3",
                "https://knut.wtf/music/Driving/Boy, Empty.mp3",
                "https://knut.wtf/music/Driving/breathe.mp3",
                "https://knut.wtf/music/Driving/Clouds.mp3",
                "https://knut.wtf/music/Driving/Controlla - Akucum Speed Up.mp3",
                "https://knut.wtf/music/Driving/Controlla - Lieless Remix.mp3",
                "https://knut.wtf/music/Driving/Deep End.mp3",
                "https://knut.wtf/music/Driving/DEFEATED.mp3",
                "https://knut.wtf/music/Driving/Did It Go Too Far.mp3",
                "https://knut.wtf/music/Driving/die (sped up).mp3",
                "https://knut.wtf/music/Driving/die.mp3",
                "https://knut.wtf/music/Driving/Don't Stop The Music - Slowed.mp3",
                "https://knut.wtf/music/Driving/Don't Stop The Music.mp3",
                "https://knut.wtf/music/Driving/ecstacy (slowed).mp3",
                "https://knut.wtf/music/Driving/ELIXIR.mp3",
                "https://knut.wtf/music/Driving/eyes don't lie.mp3",
                "https://knut.wtf/music/Driving/EYES ON ME.mp3",
                "https://knut.wtf/music/Driving/Flare.mp3",
                "https://knut.wtf/music/Driving/FUNK UNIVERSO.mp3",
                "https://knut.wtf/music/Driving/FUNKED UP - SLOWED.mp3",
                "https://knut.wtf/music/Driving/fury.mp3",
                "https://knut.wtf/music/Driving/FΛSHION.mp3",
                "https://knut.wtf/music/Driving/Genesis.mp3",
                "https://knut.wtf/music/Driving/Give It To Me.mp3",
                "https://knut.wtf/music/Driving/GOOD LOYAL THOTS.mp3",
                "https://knut.wtf/music/Driving/Guess featuring billie eilish.mp3",
                "https://knut.wtf/music/Driving/HEARTBEAT.mp3",
                "https://knut.wtf/music/Driving/HYPNOTIC DATA.mp3",
                "https://knut.wtf/music/Driving/i like the way you kiss me.mp3",
                "https://knut.wtf/music/Driving/ICEWHORE!.mp3",
                "https://knut.wtf/music/Driving/if u think i'm pretty.mp3",
                "https://knut.wtf/music/Driving/If We Being Rëal.mp3",
                "https://knut.wtf/music/Driving/KEROSENE.mp3",
                "https://knut.wtf/music/Driving/Let U Go.mp3",
                "https://knut.wtf/music/Driving/Lost In Time - Slowed.mp3",
                "https://knut.wtf/music/Driving/LOVELY BASTARDS.mp3",
                "https://knut.wtf/music/Driving/MAMACITA.mp3",
                "https://knut.wtf/music/Driving/Memories - Slowed.mp3",
                "https://knut.wtf/music/Driving/METAMORPHOSIS.mp3",
                "https://knut.wtf/music/Driving/MONEY ON THE DASH - SPED UP.mp3",
                "https://knut.wtf/music/Driving/MONTAGEM - PR FUNK.mp3",
                "https://knut.wtf/music/Driving/Montagem Mysterious Game.mp3",
                "https://knut.wtf/music/Driving/Moonlight.mp3",
                "https://knut.wtf/music/Driving/Murder In My Mind.mp3",
                "https://knut.wtf/music/Driving/NARCISSISTIC PERSONALITY DISORDER.mp3",
                "https://knut.wtf/music/Driving/Never Slow Down.mp3",
                "https://knut.wtf/music/Driving/Nightcall.mp3",
                "https://knut.wtf/music/Driving/ONE CALL.mp3",
                "https://knut.wtf/music/Driving/Out Of Touch.mp3",
                "https://knut.wtf/music/Driving/Piece of My Soul.mp3",
                "https://knut.wtf/music/Driving/Poison - Hazbin Hotel Original Soundtrack.mp3",
                "https://knut.wtf/music/Driving/Polozhenie.mp3",
                "https://knut.wtf/music/Driving/Psycho Dreams (Sped Up).mp3",
                "https://knut.wtf/music/Driving/RAVE.mp3",
                "https://knut.wtf/music/Driving/Rude Boy - slowed + reverb.mp3",
                "https://knut.wtf/music/Driving/Scars.mp3",
                "https://knut.wtf/music/Driving/Sleepwalker.mp3",
                "https://knut.wtf/music/Driving/SMOKE IT OFF!.mp3",
                "https://knut.wtf/music/Driving/SPIT IN MY FACE!.mp3",
                "https://knut.wtf/music/Driving/Stack King.mp3",
                "https://knut.wtf/music/Driving/Sunrise - Slowed & Reverb.mp3",
                "https://knut.wtf/music/Driving/TOO MANY LINES!.mp3",
                "https://knut.wtf/music/Driving/vampire heart.mp3",
                "https://knut.wtf/music/Driving/wait.mp3",
                "https://knut.wtf/music/Driving/WASTE.mp3",
                "https://knut.wtf/music/Driving/What You Waiting For_.mp3",
                "https://knut.wtf/music/Driving/Where Are You - Slowed.mp3",
                "https://knut.wtf/music/Driving/with u.mp3",
                "https://knut.wtf/music/Driving/Won't.mp3",
                "https://knut.wtf/music/Driving/wutiwant.mp3",
                "https://knut.wtf/music/Driving/zombie.mp3"].sort(() => Math.random() - 0.5)
        }
        if (cat === 'LifeStyle') {
            this.songs = [
                "https://knut.wtf/music/LifeStyle/0-100 Freestyle.mp3",
                "https://knut.wtf/music/LifeStyle/10 Bands.mp3",
                "https://knut.wtf/music/LifeStyle/Airdrop.mp3",
                "https://knut.wtf/music/LifeStyle/All The Way Up (Remix).mp3",
                "https://knut.wtf/music/LifeStyle/All Time High.mp3",
                "https://knut.wtf/music/LifeStyle/Aye.mp3",
                "https://knut.wtf/music/LifeStyle/BagBak.mp3",
                "https://knut.wtf/music/LifeStyle/Bank Account.mp3",
                "https://knut.wtf/music/LifeStyle/Bitcoin Genesis.mp3",
                "https://knut.wtf/music/LifeStyle/Bitcoin Song.mp3",
                "https://knut.wtf/music/LifeStyle/Blast Off.mp3",
                "https://knut.wtf/music/LifeStyle/Brand New Hunnids.mp3",
                "https://knut.wtf/music/LifeStyle/BTFD.mp3",
                "https://knut.wtf/music/LifeStyle/Bulls Is Back.mp3",
                "https://knut.wtf/music/LifeStyle/Buy.mp3",
                "https://knut.wtf/music/LifeStyle/Cryptocurrency.mp3",
                "https://knut.wtf/music/LifeStyle/Digital Gold.mp3",
                "https://knut.wtf/music/LifeStyle/Do You Get It (feat. DJ Mal-Ski).mp3",
                "https://knut.wtf/music/LifeStyle/Don't Hate The Game.mp3",
                "https://knut.wtf/music/LifeStyle/Dump.mp3",
                "https://knut.wtf/music/LifeStyle/Flash Drive.mp3",
                "https://knut.wtf/music/LifeStyle/Flex Up (feat. Future & Playboi Carti).mp3",
                "https://knut.wtf/music/LifeStyle/Forever, Laura.mp3",
                "https://knut.wtf/music/LifeStyle/Fuck Up Some Commas.mp3",
                "https://knut.wtf/music/LifeStyle/gm.mp3",
                "https://knut.wtf/music/LifeStyle/Going Up.mp3",
                "https://knut.wtf/music/LifeStyle/I Get Money.mp3",
                "https://knut.wtf/music/LifeStyle/I Get the Bag (feat. Migos).mp3",
                "https://knut.wtf/music/LifeStyle/Ima Boss (feat. Rick Ross).mp3",
                "https://knut.wtf/music/LifeStyle/KOD.mp3",
                "https://knut.wtf/music/LifeStyle/Lambo Snow White.mp3",
                "https://knut.wtf/music/LifeStyle/Level Up.mp3",
                "https://knut.wtf/music/LifeStyle/M'$ (feat. Lil Wayne).mp3",
                "https://knut.wtf/music/LifeStyle/Memphis, Pt. 2 (feat. NLE Choppa and A$AP Ferg).mp3",
                "https://knut.wtf/music/LifeStyle/Mo Money Mo Problems (feat. Puff Daddy & Mase) - 2014 Remaster.mp3",
                "https://knut.wtf/music/LifeStyle/Money Bag.mp3",
                "https://knut.wtf/music/LifeStyle/Money In The Grave (Drake ft. Rick Ross).mp3",
                "https://knut.wtf/music/LifeStyle/Money Longer.mp3",
                "https://knut.wtf/music/LifeStyle/Money Made Me Do It.mp3",
                "https://knut.wtf/music/LifeStyle/Money Team.mp3",
                "https://knut.wtf/music/LifeStyle/Money Trees.mp3",
                "https://knut.wtf/music/LifeStyle/Nacho Coins.mp3",
                "https://knut.wtf/music/LifeStyle/Never Enough.mp3",
                "https://knut.wtf/music/LifeStyle/New Level (feat. Future).mp3",
                "https://knut.wtf/music/LifeStyle/New Transaction.mp3",
                "https://knut.wtf/music/LifeStyle/One Chair.mp3",
                "https://knut.wtf/music/LifeStyle/Paid.mp3",
                "https://knut.wtf/music/LifeStyle/Plain Jane.mp3",
                "https://knut.wtf/music/LifeStyle/Purple Lamborghini (with Rick Ross).mp3",
                "https://knut.wtf/music/LifeStyle/Right-click-save.mp3",
                "https://knut.wtf/music/LifeStyle/Run Up the Racks.mp3",
                "https://knut.wtf/music/LifeStyle/Self Cust(OD).mp3",
                "https://knut.wtf/music/LifeStyle/Spaceman Freestyle.mp3",
                "https://knut.wtf/music/LifeStyle/The Game & Skrillex_ El Chapo.mp3",
                "https://knut.wtf/music/LifeStyle/There Is No Second Best.mp3",
                "https://knut.wtf/music/LifeStyle/Trophies.mp3",
                "https://knut.wtf/music/LifeStyle/U Mad.mp3",
                "https://knut.wtf/music/LifeStyle/WDYW (feat. Lil Uzi Vert, A$AP Ferg & Rich The Kid).mp3",
                "https://knut.wtf/music/LifeStyle/We Call Them Poor.mp3",
                "https://knut.wtf/music/LifeStyle/What's The Difference.mp3",
                "https://knut.wtf/music/LifeStyle/Where The Party At_.mp3",
                "https://knut.wtf/music/LifeStyle/Work REMIX (feat. A$AP Rocky, French Montana, Trinidad James & ScHoolboy Q).mp3"
            ].sort(() => Math.random() - 0.5)
        }
        if (cat === 'Party') {
            this.songs = [
                "https://knut.wtf/music/Party/36 Grad.mp3",
                "https://knut.wtf/music/Party/99 Luftballons - Techno.mp3",
                "https://knut.wtf/music/Party/Alibi (with Pabllo Vittar & Yseult).mp3",
                "https://knut.wtf/music/Party/Alle Haben Bock.mp3",
                "https://knut.wtf/music/Party/Allein Allein - Argy Remix.mp3",
                "https://knut.wtf/music/Party/Another World.mp3",
                "https://knut.wtf/music/Party/Apple.mp3",
                "https://knut.wtf/music/Party/Baby, You're the One (Whole Again).mp3",
                "https://knut.wtf/music/Party/Be My Lover (feat. La Bouche) - 2023 Mix.mp3",
                "https://knut.wtf/music/Party/Belly Dancer.mp3",
                "https://knut.wtf/music/Party/Bittersweet Goodbye.mp3",
                "https://knut.wtf/music/Party/Blonde Chaya - Niklas Dee & Pytro Remix.mp3",
                "https://knut.wtf/music/Party/Break The Rules.mp3",
                "https://knut.wtf/music/Party/Breaking Me - HUGEL Remix.mp3",
                "https://knut.wtf/music/Party/California Dreamin'.mp3",
                "https://knut.wtf/music/Party/Can't Forget You (Club Mix).mp3",
                "https://knut.wtf/music/Party/Clap Clap (Techno).mp3",
                "https://knut.wtf/music/Party/COACHELLA.mp3",
                "https://knut.wtf/music/Party/Complicated - Techno Remix.mp3",
                "https://knut.wtf/music/Party/Conga.mp3",
                "https://knut.wtf/music/Party/Cynical - Teenage Mutants Remix.mp3",
                "https://knut.wtf/music/Party/Dance For Me (Family Affair) - Radio Edit.mp3",
                "https://knut.wtf/music/Party/Dancing Queen.mp3",
                "https://knut.wtf/music/Party/Danza Kuduro - Tiësto Remix.mp3",
                "https://knut.wtf/music/Party/Der Berg ruft.mp3",
                "https://knut.wtf/music/Party/Destination Calabria.mp3",
                "https://knut.wtf/music/Party/DEUTSCHLAND 🇩🇪 (MIT IKKIMEL).mp3",
                "https://knut.wtf/music/Party/Dieses Leben.mp3",
                "https://knut.wtf/music/Party/Don't Stop Believin'.mp3",
                "https://knut.wtf/music/Party/Drugs From Amsterdam.mp3",
                "https://knut.wtf/music/Party/Espresso.mp3",
                "https://knut.wtf/music/Party/Explode.mp3",
                "https://knut.wtf/music/Party/FE!N (feat. Playboi Carti).mp3",
                "https://knut.wtf/music/Party/Feeling Good.mp3",
                "https://knut.wtf/music/Party/For You - Fabian Farell Remix.mp3",
                "https://knut.wtf/music/Party/Freak.mp3",
                "https://knut.wtf/music/Party/Fuego.mp3",
                "https://knut.wtf/music/Party/Geiles Leben.mp3",
                "https://knut.wtf/music/Party/Germany & Techno.mp3",
                "https://knut.wtf/music/Party/Gimme Gimme Gimme.mp3",
                "https://knut.wtf/music/Party/He's A Pirate (Save Me).mp3",
                "https://knut.wtf/music/Party/Hollow (feat. Bonn).mp3",
                "https://knut.wtf/music/Party/Hot N' Cold - HYPERTECHNO.mp3",
                "https://knut.wtf/music/Party/Hotel Room Service.mp3",
                "https://knut.wtf/music/Party/I Love It.mp3",
                "https://knut.wtf/music/Party/I Wouldn't Mind.mp3",
                "https://knut.wtf/music/Party/I'm Good (Blue).mp3",
                "https://knut.wtf/music/Party/In Your Arms (Something).mp3",
                "https://knut.wtf/music/Party/International Love (feat. Chris Brown).mp3",
                "https://knut.wtf/music/Party/Intoxicated - Hypertechno.mp3",
                "https://knut.wtf/music/Party/INZIDANCE.mp3",
                "https://knut.wtf/music/Party/It Girl (feat. Sampagne).mp3",
                "https://knut.wtf/music/Party/It's ok I'm ok.mp3",
                "https://knut.wtf/music/Party/Jim Beam & Voddi.mp3",
                "https://knut.wtf/music/Party/Knockin'.mp3",
                "https://knut.wtf/music/Party/Let Me Think About It Again.mp3",
                "https://knut.wtf/music/Party/LET'S GET FKD UP.mp3",
                "https://knut.wtf/music/Party/Levels - Techno-Rave Mix.mp3",
                "https://knut.wtf/music/Party/Liebe auf den ersten Beat.mp3",
                "https://knut.wtf/music/Party/Liebe Grüsse.mp3",
                "https://knut.wtf/music/Party/Live Your Life.mp3",
                "https://knut.wtf/music/Party/Losing It.mp3",
                "https://knut.wtf/music/Party/Make It Hot - DJ Kuba & Neitan Edit.mp3",
                "https://knut.wtf/music/Party/Mama hat gesagt - Gestört aber GeiL Remix.mp3",
                "https://knut.wtf/music/Party/Man In Finance (with David Guetta).mp3",
                "https://knut.wtf/music/Party/Mas Gasolina.mp3",
                "https://knut.wtf/music/Party/Meet Her At The Love Parade.mp3",
                "https://knut.wtf/music/Party/Memories - Club Mix.mp3",
                "https://knut.wtf/music/Party/Millionen Lichter (Das Boot).mp3",
                "https://knut.wtf/music/Party/Miss You Love (DJ SaLVa Edit).mp3",
                "https://knut.wtf/music/Party/Moment.mp3",
                "https://knut.wtf/music/Party/More - Techno Mix.mp3",
                "https://knut.wtf/music/Party/Move Your Body - Tiësto Edit.mp3",
                "https://knut.wtf/music/Party/Mwaki (Techno Edit).mp3",
                "https://knut.wtf/music/Party/Never Be Lonely - Scooter Remix.mp3",
                "https://knut.wtf/music/Party/Now Or Never.mp3",
                "https://knut.wtf/music/Party/Ohne mein Team.mp3",
                "https://knut.wtf/music/Party/On The Floor - DJSM Remix.mp3",
                "https://knut.wtf/music/Party/Party Sahne.mp3",
                "https://knut.wtf/music/Party/Pieces.mp3",
                "https://knut.wtf/music/Party/Primo.mp3",
                "https://knut.wtf/music/Party/Push Up - Main Edit.mp3",
                "https://knut.wtf/music/Party/Rhythm Is A Dancer - Chrit Leaf Remix.mp3",
                "https://knut.wtf/music/Party/Satisfied.mp3",
                "https://knut.wtf/music/Party/SexyBack - TechnoBack.mp3",
                "https://knut.wtf/music/Party/Somebody To Love.mp3",
                "https://knut.wtf/music/Party/Sweat - Remix.mp3",
                "https://knut.wtf/music/Party/Temperamento.mp3",
                "https://knut.wtf/music/Party/Thank You (Not So Bad).mp3",
                "https://knut.wtf/music/Party/The Way I Are.mp3",
                "https://knut.wtf/music/Party/Think About The Way.mp3",
                "https://knut.wtf/music/Party/UNSTERBLICH.mp3",
                "https://knut.wtf/music/Party/VEMPA - Shirli Version.mp3",
                "https://knut.wtf/music/Party/Von Party zu Party.mp3",
                "https://knut.wtf/music/Party/We Are Young - Sound Factory Edit.mp3",
                "https://knut.wtf/music/Party/Where Did You Go_ - A1 x J1 Remix.mp3",
                "https://knut.wtf/music/Party/Wicked Game.mp3",
                "https://knut.wtf/music/Party/Willst du - Achtabahn Remix.mp3",
                "https://knut.wtf/music/Party/Wünsch dir was.mp3",
                "https://knut.wtf/music/Party/Yeah! (feat. Lil Jon & Ludacris).mp3"
            ].sort(() => Math.random() - 0.5)
        }
        if (cat === 'Relaxation') {
            this.songs = [
                "https://knut.wtf/music/Relaxation/432 Hz Zen - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/528 Hz Anxiety Relief - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/528 Hz Divine Frequency Flow - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/528 Hz Harmonic Healing Journey - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/528 Hz Meditation - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/528 Hz Soulful Resonance - 8D audio.mp3",
                "https://knut.wtf/music/Relaxation/528 Hz Universal Love Vibration - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/852 Hz Awakening Whispers - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/852 Hz Empowerment Echoes - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/852 Hz Healing Frequency - 8D audio.mp3",
                "https://knut.wtf/music/Relaxation/8D Audio Zen.mp3",
                "https://knut.wtf/music/Relaxation/8D Meditation Music.mp3",
                "https://knut.wtf/music/Relaxation/8D Relax Music.mp3",
                "https://knut.wtf/music/Relaxation/8D Relaxing Brain Massage.mp3",
                "https://knut.wtf/music/Relaxation/8D Relaxing Meditation Music.mp3",
                "https://knut.wtf/music/Relaxation/Abundance Meditation - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Beautiful Piano Ambient - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Blissful Aura - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Blissful Relief - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Blissful Serenity - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Carefree Sleep - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Celestial Whispers - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Cosmic Vibrations - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Deep Peace - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Deep Theta Meditation - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Deep Thinking - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Dissolve Into Serenity.mp3",
                "https://knut.wtf/music/Relaxation/Divine Healing Frequencies - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Dream State - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Dreamy Nightfall - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Echoes Beyond Time.mp3",
                "https://knut.wtf/music/Relaxation/Echoes of Serenity - 8D audio.mp3",
                "https://knut.wtf/music/Relaxation/Echoes of the Soul.mp3",
                "https://knut.wtf/music/Relaxation/Enchanted Reverie.mp3",
                "https://knut.wtf/music/Relaxation/Escape From Anxiety.mp3",
                "https://knut.wtf/music/Relaxation/Eternal Ebb.mp3",
                "https://knut.wtf/music/Relaxation/Ethereal Bliss - 8D audio.mp3",
                "https://knut.wtf/music/Relaxation/Ethereal Tranquility - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Find Tranquility - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Floating In The Clouds - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Flow of Silence - 8D audio.mp3",
                "https://knut.wtf/music/Relaxation/Flowing Into Peace.mp3",
                "https://knut.wtf/music/Relaxation/Focused Mind - 8D audio.mp3",
                "https://knut.wtf/music/Relaxation/Garden of Peace - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Harmonic Bliss - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Healing Meditation - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Healing Music Therapy - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Impassivity - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Inner Balance - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Inner Ocean.mp3",
                "https://knut.wtf/music/Relaxation/Inner Peace - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Inner Peace Symphony - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Journey Through The Galaxy.mp3",
                "https://knut.wtf/music/Relaxation/Journey to Stillness - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Lonely Angel - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Luminous Horizons.mp3",
                "https://knut.wtf/music/Relaxation/Meditation - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Meditation For The Soul - 8D audio.mp3",
                "https://knut.wtf/music/Relaxation/Meditation Sleep Music - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Meditative Melancholy - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Meditative Mind - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Melodies Of Tranquility - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Mind Relaxation 8D Audio - 8D audio.mp3",
                "https://knut.wtf/music/Relaxation/Mind Relaxation 8D Audio.mp3",
                "https://knut.wtf/music/Relaxation/Mindful Journey - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Mindfulness Meditation - 8D audio.mp3",
                "https://knut.wtf/music/Relaxation/Mystical Serenity - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Nature's Embrace.mp3",
                "https://knut.wtf/music/Relaxation/Part Of Nature - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Peace Of Mind - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Peace Of Mind.mp3",
                "https://knut.wtf/music/Relaxation/Peaceful Escape - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Quiet Dreams.mp3",
                "https://knut.wtf/music/Relaxation/Reflections - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Relaxing Hang Drum - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Relaxing Morning - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Relaxing Oasis - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Sacred Harmonies of Healing - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Serene Dream.mp3",
                "https://knut.wtf/music/Relaxation/Serene Solace - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Serenity's Embrace - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Silent Mind - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Sleep Peacefully - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Soul Serenity - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Space Energy.mp3",
                "https://knut.wtf/music/Relaxation/Stream Of Peace - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Stressless State - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Theta Meditation 528 Hz - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Timeless Tranquility - 8D audio.mp3",
                "https://knut.wtf/music/Relaxation/Tranquil Ease - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Tranquil Oasis - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Tranquil Reflections - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Tranquil Waves - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Transcendental Harmony - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Voice Of Space.mp3",
                "https://knut.wtf/music/Relaxation/When It Rains - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Whispers of Infinity.mp3",
                "https://knut.wtf/music/Relaxation/Zen Garden - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Zen Garden Melodies - 8D AUDIO.mp3",
                "https://knut.wtf/music/Relaxation/Zero Gravity - 8D AUDIO.mp3"
            ].sort(() => Math.random() - 0.5)
        }
        if (cat === 'Romantic') {
            this.songs = [
                "https://knut.wtf/music/Romantic/A Thousand Years (Intro).mp3",
                "https://knut.wtf/music/Romantic/A Thousand Years.mp3",
                "https://knut.wtf/music/Romantic/Adore You.mp3",
                "https://knut.wtf/music/Romantic/All I Want - From _High School Musical_ The Musical_ The Series_.mp3",
                "https://knut.wtf/music/Romantic/All Of Me.mp3",
                "https://knut.wtf/music/Romantic/Anti-Hero.mp3",
                "https://knut.wtf/music/Romantic/Are You With Me.mp3",
                "https://knut.wtf/music/Romantic/As It Was.mp3",
                "https://knut.wtf/music/Romantic/Blameless.mp3",
                "https://knut.wtf/music/Romantic/Blinding Lights.mp3",
                "https://knut.wtf/music/Romantic/Blow The Blue Away.mp3",
                "https://knut.wtf/music/Romantic/Burning Bridges.mp3",
                "https://knut.wtf/music/Romantic/Burning Love.mp3",
                "https://knut.wtf/music/Romantic/Can't Forget Interlude.mp3",
                "https://knut.wtf/music/Romantic/Can't Help Falling in Love.mp3",
                "https://knut.wtf/music/Romantic/cardigan.mp3",
                "https://knut.wtf/music/Romantic/Catching Feelings.mp3",
                "https://knut.wtf/music/Romantic/Chasing Cars.mp3",
                "https://knut.wtf/music/Romantic/Dance The Night - From Barbie The Album.mp3",
                "https://knut.wtf/music/Romantic/Don't Go Yet.mp3",
                "https://knut.wtf/music/Romantic/Drink You Up.mp3",
                "https://knut.wtf/music/Romantic/Easy On Me.mp3",
                "https://knut.wtf/music/Romantic/Every Breath You Take.mp3",
                "https://knut.wtf/music/Romantic/Eyes Are Blue.mp3",
                "https://knut.wtf/music/Romantic/Fantasy.mp3",
                "https://knut.wtf/music/Romantic/Five Seconds of Fame.mp3",
                "https://knut.wtf/music/Romantic/Fix You.mp3",
                "https://knut.wtf/music/Romantic/For You [Fifty Shades Freed].mp3",
                "https://knut.wtf/music/Romantic/Forget Me.mp3",
                "https://knut.wtf/music/Romantic/Free Fallin'.mp3",
                "https://knut.wtf/music/Romantic/Guide Me Home.mp3",
                "https://knut.wtf/music/Romantic/Happier.mp3",
                "https://knut.wtf/music/Romantic/Heart Beats.mp3",
                "https://knut.wtf/music/Romantic/Hollow Dream.mp3",
                "https://knut.wtf/music/Romantic/How Long Will I Love You.mp3",
                "https://knut.wtf/music/Romantic/I Just Called To Say I Love You.mp3",
                "https://knut.wtf/music/Romantic/I'm Yours.mp3",
                "https://knut.wtf/music/Romantic/If I Ain't Got You.mp3",
                "https://knut.wtf/music/Romantic/In The Ghetto.mp3",
                "https://knut.wtf/music/Romantic/In The Name Of Love.mp3",
                "https://knut.wtf/music/Romantic/It'll Be Okay.mp3",
                "https://knut.wtf/music/Romantic/Just One Love.mp3",
                "https://knut.wtf/music/Romantic/Just the Way You Are.mp3",
                "https://knut.wtf/music/Romantic/L-O-V-E.mp3",
                "https://knut.wtf/music/Romantic/Lavender Haze.mp3",
                "https://knut.wtf/music/Romantic/Left Behind.mp3",
                "https://knut.wtf/music/Romantic/Let Her Go.mp3",
                "https://knut.wtf/music/Romantic/Like Us (with Marin Hoxha).mp3",
                "https://knut.wtf/music/Romantic/Loser.mp3",
                "https://knut.wtf/music/Romantic/Love Me Like You Do.mp3",
                "https://knut.wtf/music/Romantic/Love Someone.mp3",
                "https://knut.wtf/music/Romantic/Love Will Lead Us There.mp3",
                "https://knut.wtf/music/Romantic/Love Will Tear Us Apart.mp3",
                "https://knut.wtf/music/Romantic/Love's Hard Landing.mp3",
                "https://knut.wtf/music/Romantic/Lover.mp3",
                "https://knut.wtf/music/Romantic/Make You Feel My Love.mp3",
                "https://knut.wtf/music/Romantic/Memories.mp3",
                "https://knut.wtf/music/Romantic/My Mind & Me.mp3",
                "https://knut.wtf/music/Romantic/Never Reply.mp3",
                "https://knut.wtf/music/Romantic/No Other (Acoustic).mp3",
                "https://knut.wtf/music/Romantic/Numb Pill.mp3",
                "https://knut.wtf/music/Romantic/One Life.mp3",
                "https://knut.wtf/music/Romantic/One More Minute.mp3",
                "https://knut.wtf/music/Romantic/Palms (with Little Rain).mp3",
                "https://knut.wtf/music/Romantic/Permanent (acoustic).mp3",
                "https://knut.wtf/music/Romantic/Picasso.mp3",
                "https://knut.wtf/music/Romantic/Put Your Records On.mp3",
                "https://knut.wtf/music/Romantic/Reciprocity.mp3",
                "https://knut.wtf/music/Romantic/Renegades.mp3",
                "https://knut.wtf/music/Romantic/Rest.mp3",
                "https://knut.wtf/music/Romantic/Say You Won't Let Go.mp3",
                "https://knut.wtf/music/Romantic/Self Sabotage.mp3",
                "https://knut.wtf/music/Romantic/Selfish.mp3",
                "https://knut.wtf/music/Romantic/Shallow - Intro.mp3",
                "https://knut.wtf/music/Romantic/Shallow.mp3",
                "https://knut.wtf/music/Romantic/Someone You Loved.mp3",
                "https://knut.wtf/music/Romantic/Sorry.mp3",
                "https://knut.wtf/music/Romantic/Stand By Me.mp3",
                "https://knut.wtf/music/Romantic/Stay With Me.mp3",
                "https://knut.wtf/music/Romantic/The Deeper I Fall.mp3",
                "https://knut.wtf/music/Romantic/Toxic To You (Remix).mp3",
                "https://knut.wtf/music/Romantic/Treat You Better.mp3",
                "https://knut.wtf/music/Romantic/True Colours.mp3",
                "https://knut.wtf/music/Romantic/Turn Me On.mp3",
                "https://knut.wtf/music/Romantic/Undercurrent.mp3",
                "https://knut.wtf/music/Romantic/Vegas.mp3",
                "https://knut.wtf/music/Romantic/Wake Me Up - Acoustic Guitar & Saxophone Edit.mp3",
                "https://knut.wtf/music/Romantic/What I Deserve.mp3",
                "https://knut.wtf/music/Romantic/What I Was Made For.mp3",
                "https://knut.wtf/music/Romantic/When The Sun Goes Down.mp3",
                "https://knut.wtf/music/Romantic/Wonderwall.mp3",
                "https://knut.wtf/music/Romantic/You Are The Reason.mp3",
                "https://knut.wtf/music/Romantic/You Found Me.mp3",
                "https://knut.wtf/music/Romantic/You're Beautiful.mp3",
                "https://knut.wtf/music/Romantic/You're The One.mp3",
                "https://knut.wtf/music/Romantic/You've Got The Love.mp3",
                "https://knut.wtf/music/Romantic/Your Song.mp3"
            ].sort(() => Math.random() - 0.5)
        }
        if (cat === 'Workouts') {
            this.songs = [
                "https://knut.wtf/music/Workouts/All That She Wants.mp3",
                "https://knut.wtf/music/Workouts/Around the World (La La La La La) - Radio Version.mp3",
                "https://knut.wtf/music/Workouts/Bailando - Energia Mix Short Version.mp3",
                "https://knut.wtf/music/Workouts/Barbie Girl.mp3",
                "https://knut.wtf/music/Workouts/Because the Night.mp3",
                "https://knut.wtf/music/Workouts/Blue (Da Ba Dee).mp3",
                "https://knut.wtf/music/Workouts/Boom, Boom, Boom, Boom!!.mp3",
                "https://knut.wtf/music/Workouts/Boten Anna - Club Remix.mp3",
                "https://knut.wtf/music/Workouts/Call On Me - Radio Edit.mp3",
                "https://knut.wtf/music/Workouts/Captain Jack - Short Mix.mp3",
                "https://knut.wtf/music/Workouts/Coco Jamboo - Radio Version.mp3",
                "https://knut.wtf/music/Workouts/Cotton Eye Joe.mp3",
                "https://knut.wtf/music/Workouts/Das geht ab (Wir feiern die ganze Nacht).mp3",
                "https://knut.wtf/music/Workouts/Dragostea Din Tei.mp3",
                "https://knut.wtf/music/Workouts/Eins Zwei Polizei - Gendarmerie Mix.mp3",
                "https://knut.wtf/music/Workouts/Everybody (Backstreet's Back) - Radio Edit.mp3",
                "https://knut.wtf/music/Workouts/Freed From Desire - prod. Molella, Phil Jay.mp3",
                "https://knut.wtf/music/Workouts/Get Down (You're the One for Me) - LP Edit No Rap.mp3",
                "https://knut.wtf/music/Workouts/Hamma!.mp3",
                "https://knut.wtf/music/Workouts/Herz an Herz.mp3",
                "https://knut.wtf/music/Workouts/How Much Is the Fish_.mp3",
                "https://knut.wtf/music/Workouts/I Kissed A Girl.mp3",
                "https://knut.wtf/music/Workouts/I Like to Move It - '93 Radio Edit.mp3",
                "https://knut.wtf/music/Workouts/Infinity 2008 - Klaas Vocal Edit.mp3",
                "https://knut.wtf/music/Workouts/La Di Da - Dance Mix Short.mp3",
                "https://knut.wtf/music/Workouts/Larger Than Life.mp3",
                "https://knut.wtf/music/Workouts/Macarena - Bayside Boys Remix.mp3",
                "https://knut.wtf/music/Workouts/Mambo No. 5 (A Little Bit of...).mp3",
                "https://knut.wtf/music/Workouts/Maria (I Like It Loud).mp3",
                "https://knut.wtf/music/Workouts/Memories (feat. Kid Cudi).mp3",
                "https://knut.wtf/music/Workouts/Monsta.mp3",
                "https://knut.wtf/music/Workouts/Moonlight Shadow - Original Mix.mp3",
                "https://knut.wtf/music/Workouts/Mr. Vain Recall - Radio Edit.mp3",
                "https://knut.wtf/music/Workouts/Narcotic - Radio Edit.mp3",
                "https://knut.wtf/music/Workouts/Nessaja.mp3",
                "https://knut.wtf/music/Workouts/Nur Geträumt.mp3",
                "https://knut.wtf/music/Workouts/Oops!...I Did It Again.mp3",
                "https://knut.wtf/music/Workouts/Party Mix II.mp3",
                "https://knut.wtf/music/Workouts/Quit Playing Games (With My Heart).mp3",
                "https://knut.wtf/music/Workouts/Rhythm Is A Dancer - 7_ Edit.mp3",
                "https://knut.wtf/music/Workouts/Saturday Night - Radio Mix.mp3",
                "https://knut.wtf/music/Workouts/Sexy Bitch (feat. Akon).mp3",
                "https://knut.wtf/music/Workouts/Sing Hallelujah!.mp3",
                "https://knut.wtf/music/Workouts/Stamp On The Ground.mp3",
                "https://knut.wtf/music/Workouts/Summer Jam - Radio Edit.mp3",
                "https://knut.wtf/music/Workouts/Sweet Dreams.mp3",
                "https://knut.wtf/music/Workouts/Tearin' up My Heart - Radio Edit.mp3",
                "https://knut.wtf/music/Workouts/Teenage Dirtbag.mp3",
                "https://knut.wtf/music/Workouts/The Rhythm of the Night.mp3",
                "https://knut.wtf/music/Workouts/The Rigga Ding Dong Song - Radio Version.mp3",
                "https://knut.wtf/music/Workouts/The Sign.mp3",
                "https://knut.wtf/music/Workouts/The Spirit of the Hawk.mp3",
                "https://knut.wtf/music/Workouts/There Is a Party.mp3",
                "https://knut.wtf/music/Workouts/This Is How We Do It.mp3",
                "https://knut.wtf/music/Workouts/Turn Around (5,4,3,2,1).mp3",
                "https://knut.wtf/music/Workouts/U Can't Touch This.mp3",
                "https://knut.wtf/music/Workouts/U Got 2 Let The Music.mp3",
                "https://knut.wtf/music/Workouts/Verdammt ich lieb dich - Remastered.mp3",
                "https://knut.wtf/music/Workouts/Wannabe.mp3",
                "https://knut.wtf/music/Workouts/Welcome to the Club - Video Edit.mp3",
                "https://knut.wtf/music/Workouts/We’re Going to Ibiza!.mp3",
                "https://knut.wtf/music/Workouts/What Is Love - 7_ Mix.mp3",
                "https://knut.wtf/music/Workouts/Whatcha Say.mp3",
                "https://knut.wtf/music/Workouts/Wonderful Days (2001 Radio Edit).mp3",
                "https://knut.wtf/music/Workouts/Word Of Mouth.mp3",
                "https://knut.wtf/music/Workouts/Yeah!.mp3",
                "https://knut.wtf/music/Workouts/You - Single Edit.mp3",
                "https://knut.wtf/music/Workouts/You're My Mate.mp3",
                "https://knut.wtf/music/Workouts/Zeitmaschine - 90s Mix.mp3"
            ].sort(() => Math.random() - 0.5)
        }
        if (cat === 'FRED') {
            this.songs = [
                "https://knut.wtf/music/Fred/adore u.mp3",
                "https://knut.wtf/music/Fred/Baby again...mp3",
                "https://knut.wtf/music/Fred/backseat.mp3",
                "https://knut.wtf/music/Fred/Baxter (these are my friends).mp3",
                "https://knut.wtf/music/Fred/BerwynGesaffNeighbours.mp3",
                "https://knut.wtf/music/Fred/Billie (loving arms).mp3",
                "https://knut.wtf/music/Fred/Bleu (better with time).mp3",
                "https://knut.wtf/music/Fred/Clara (the night is dark).mp3",
                "https://knut.wtf/music/Fred/Cmon.mp3",
                "https://knut.wtf/music/Fred/Danielle (smile on my face).mp3",
                "https://knut.wtf/music/Fred/Delilah (pull me out of this).mp3",
                "https://knut.wtf/music/Fred/Dermot (see yourself in my eyes).mp3",
                "https://knut.wtf/music/Fred/Faisal (envelops me).mp3",
                "https://knut.wtf/music/Fred/fear less.mp3",
                "https://knut.wtf/music/Fred/glow.mp3",
                "https://knut.wtf/music/Fred/Hannah (the sun).mp3",
                "https://knut.wtf/music/Fred/i saw you.mp3",
                "https://knut.wtf/music/Fred/Jessie (i miss you).mp3",
                "https://knut.wtf/music/Fred/Julia (deep diving).mp3",
                "https://knut.wtf/music/Fred/Jungle.mp3",
                "https://knut.wtf/music/Fred/just stand there.mp3",
                "https://knut.wtf/music/Fred/Kammy (like i do).mp3",
                "https://knut.wtf/music/Fred/Kyle (i found you).mp3",
                "https://knut.wtf/music/Fred/leavemealone.mp3",
                "https://knut.wtf/music/Fred/Lights Out.mp3",
                "https://knut.wtf/music/Fred/Marea (we’ve lost dancing).mp3",
                "https://knut.wtf/music/Fred/Me (heavy).mp3",
                "https://knut.wtf/music/Fred/peace u need.mp3",
                "https://knut.wtf/music/Fred/places to be.mp3",
                "https://knut.wtf/music/Fred/Roze (forgive).mp3",
                "https://knut.wtf/music/Fred/Rumble.mp3",
                "https://knut.wtf/music/Fred/stayinit.mp3",
                "https://knut.wtf/music/Fred/Strong.mp3",
                "https://knut.wtf/music/Fred/Tate (how i feel).mp3",
                "https://knut.wtf/music/Fred/ten.mp3",
                "https://knut.wtf/music/Fred/Turn On The Lights again.. (feat. Future & Fred again..) - Anyma Remix.mp3",
                "https://knut.wtf/music/Fred/Turn On The Lights again.. (feat. Future).mp3",
                "https://knut.wtf/music/Fred/Yasminah (see your face again).mp3"
            ].sort(() => Math.random() - 0.5)
        }
        this.category = cat;
        this.nextSong();
    }


}

export default new AudioStore();